modLoader="javafml"
loaderVersion="[47,)"
license="All credit coems back to me"

[[mods]]
modId="betterore"
version="1.1.0"
displayName="better Ores"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Axel_Dademin, MCreator"
description="Better Ores + is a mod to give your game a new glance into farming and ores, with new tools, ores, armor and item, but aslo a new biome! All credit to myself, you can find me on any platform with my user \"Axel_Dademon\" but you cna add me trough discord <3"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.betterore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration